-- CREATE TABLE passport
-- (
--     id              UUID,
--     first_name      VARCHAR(255),
--     last_name       VARCHAR(255),
--     surname         VARCHAR(255),
--     serial_passport INTEGER,
--     number_passport INTEGER
-- );