-- ALTER TABLE passport
--     ADD created_date TIMESTAMP WITHOUT TIME ZONE;
--
-- ALTER TABLE passport
--     ADD version INTEGER;
--
-- ALTER TABLE passport
--     ALTER COLUMN version SET NOT NULL;